schemaVersion: 1
sessionDefaults:
  projectPath: KeiBA.xcodeproj
  scheme: KeiBA
  configuration: Debug
  simulatorName: iPhone 17 Pro
  simulatorId: 74D3B695-3683-441F-851D-90B3A982FAF8
  useLatestOS: true
  bundleId: os.kei.KeiBA
  simulatorPlatform: iOS Simulator
