schemaVersion: 1
sessionDefaults:
  projectPath: /Users/voyager/voyager space/iOSGit/KeiBAOS/KeiBAOS.xcodeproj
  scheme: KeiBAOS
  configuration: Debug
  simulatorName: iPhone 17 Pro
  simulatorId: 74D3B695-3683-441F-851D-90B3A982FAF8
  useLatestOS: true
  bundleId: os.kei.KeiBAOS
  simulatorPlatform: iOS Simulator
